/**
 * OpenFangRawEditor.jsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Raw TOML config editor for OpenFang (~/.openfang/config.toml).
 * Mirrors the RawConfigEditor UX (Monaco, history, save & restart)
 * but reads/writes TOML instead of JSON via dedicated IPC handlers.
 */

import React, { useState, useEffect, useRef } from 'react';
import Editor from '@monaco-editor/react';
import { Save, PlaySquare, Maximize, Minimize, History, Clock, CheckCircle2, AlertTriangle } from 'lucide-react';
import { toast } from '../Toast/Toast';

const OpenFangRawEditor = ({ platform, onSaveAndRestart, isFullscreen, onToggleFullscreen }) => {
  const [content, setContent] = useState('# Loading...');
  const [loading, setLoading] = useState(true);
  const [history, setHistory] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const editorRef = useRef(null);

  useEffect(() => {
    loadConfig();
    loadHistory();
    
    // Listen for external file changes
    const handleConfigChange = ({ platformId, filename }) => {
      if (platformId === 'openfang' && !isDirty) {
        toast.info(`External config change detected (${filename}), auto-reloading...`);
        loadConfig();
      }
    };
    
    // electron.ipcRenderer.on returns the unsubscription function
    const unsubscribe = window.electron?.ipcRenderer.on('config-file-changed', handleConfigChange);
    return () => {
      if (unsubscribe) unsubscribe();
    };
  }, [platform?.id, isDirty]);

  const TOML_TEMPLATE = `# ~/.openfang/config.toml
# Auto-generated by ClawExpress. Edit and Save & Restart to apply.
# Full reference: https://openfang.sh/docs/configuration

[channels]
# Enable channels here. Example:
# [channels.telegram]
# api_key_env = "TELEGRAM_BOT_TOKEN"
#
# [channels.discord]
# api_key_env = "DISCORD_BOT_TOKEN"

[agents]
# [agents.defaults]
# model = "deepseek-chat"
`;

  const loadConfig = async () => {
    setLoading(true);
    try {
      const res = await window.electron?.ipcRenderer.invoke('read-raw-config', { platformId: 'openfang' });
      if (res?.success) {
        setContent(res.text);
        setIsDirty(false);
      } else {
        // File doesn't exist yet — show a helpful template, not an error
        setContent(TOML_TEMPLATE);
        setIsDirty(false);
      }
    } catch (_) {
      // Handler not yet registered (main process not restarted) — show template
      setContent(TOML_TEMPLATE);
      setIsDirty(false);
    } finally {
      setLoading(false);
    }
  };

  const loadHistory = async () => {
    try {
      const res = await window.electron?.ipcRenderer.invoke('get-config-history', { platformId: 'openfang' });
      if (res?.success) setHistory(res.history || []);
    } catch (_) { /* handler not yet registered — ignore */ }
  };

  const handleChange = (value) => {
    setContent(value);
    setIsDirty(true);
  };

  const handleEditorDidMount = (editor) => {
    editorRef.current = editor;
  };

  const performSave = async (shouldRestart) => {
    const text = editorRef.current?.getValue() ?? content;
    try {
      const res = await window.electron?.ipcRenderer.invoke('write-raw-config', { platformId: 'openfang', rawToml: text });
      if (res?.success) {
        setIsDirty(false);
        toast.success(shouldRestart ? 'config.toml saved — restarting…' : 'config.toml saved!');
        loadHistory();
        if (shouldRestart) onSaveAndRestart?.();
      } else {
        toast.error(`Save failed: ${res?.reason}`);
      }
    } catch (e) {
      toast.error('Error saving config.toml');
    }
  };

  const restoreHistory = async (filename) => {
    if (!window.confirm(`Restore from ${filename}? Current changes will be lost.`)) return;
    try {
      const res = await window.electron?.ipcRenderer.invoke('restore-config-history', { platformId: 'openfang', filename });
      if (res?.success) {
        setContent(res.text);
        setIsDirty(true);
        toast.success('Restored. Review then Save & Restart to apply.');
        setShowHistory(false);
      } else {
        toast.error(`Restore failed: ${res?.reason}`);
      }
    } catch (e) {
      toast.error('Error restoring history');
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: '12px', flex: 1, minHeight: '400px' }}>
      {/* Toolbar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <p style={{ fontSize: '13px', color: 'var(--text-muted)', margin: 0, paddingLeft: '4px' }}>
          Edit <code style={{ fontSize: '12px', color: 'rgba(139,92,246,0.9)' }}>~/.openfang/config.toml</code> directly.
          Changes are written to disk; restart to apply.
        </p>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={onToggleFullscreen}
            style={btnStyle}
          >
            {isFullscreen ? <><Minimize size={13} /> Exit Fullscreen</> : <><Maximize size={13} /> Fullscreen</>}
          </button>

          {/* History dropdown */}
          <div style={{ position: 'relative' }}>
            <button onClick={() => setShowHistory(!showHistory)} style={btnStyle}>
              <History size={13} /> {showHistory ? 'Hide History' : 'History'}
            </button>
            {showHistory && (
              <div style={{
                position: 'absolute', right: 0, top: 'calc(100% + 5px)', zIndex: 10,
                background: 'var(--bg-secondary)', border: '1px solid var(--border-color)',
                borderRadius: '6px', minWidth: '220px', maxHeight: '250px', overflowY: 'auto',
                boxShadow: '0 4px 12px rgba(0,0,0,0.5)', padding: '8px 0'
              }}>
                <div style={{ padding: '4px 12px', fontSize: '11px', color: 'var(--text-muted)', fontWeight: 600, borderBottom: '1px solid var(--border-color)', marginBottom: '4px' }}>
                  Recent Backups
                </div>
                {history.length === 0 ? (
                  <div style={{ padding: '8px 12px', fontSize: '12px', color: 'var(--text-muted)' }}>No history yet.</div>
                ) : history.map(h => (
                  <div
                    key={h.filename}
                    onClick={() => restoreHistory(h.filename)}
                    style={{ padding: '6px 12px', fontSize: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-primary)' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                  >
                    <Clock size={11} color="var(--text-muted)" /> {h.dateStr}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Monaco Editor */}
      <div style={{ flex: 1, borderRadius: '8px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.1)' }}>
        {loading ? (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)', fontSize: '13px' }}>
            Loading Editor…
          </div>
        ) : (
          <Editor
            height="100%"
            defaultLanguage="ini"
            theme="vs-dark"
            value={content}
            onChange={handleChange}
            onMount={handleEditorDidMount}
            options={{
              minimap: { enabled: false },
              fontSize: 13,
              fontFamily: '"Fira Code", monospace',
              scrollBeyondLastLine: false,
              wordWrap: 'on',
            }}
          />
        )}
      </div>

      {/* Footer / Save buttons */}
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '12px', background: 'rgba(0,0,0,0.2)', borderRadius: '8px',
        border: '1px solid rgba(255,255,255,0.05)'
      }}>
        <div>
          {isDirty ? (
            <span style={{ color: '#f59e0b', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <AlertTriangle size={14} /> Unsaved changes
            </span>
          ) : (
            <span style={{ color: '#22c55e', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '6px', opacity: 0.8 }}>
              <CheckCircle2 size={14} /> Saved
            </span>
          )}
        </div>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button onClick={() => performSave(false)} style={saveBtn(false)}>
            <Save size={14} /> Save
          </button>
          <button onClick={() => performSave(true)} style={saveBtn(true)}>
            <PlaySquare size={14} /> Save &amp; Restart
          </button>
        </div>
      </div>
    </div>
  );
};

const btnStyle = {
  background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
  color: 'var(--text-primary)', padding: '5px 10px', borderRadius: '5px',
  cursor: 'pointer', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '6px',
  fontFamily: 'var(--font-primary)',
};

const saveBtn = (primary) => ({
  background: primary ? 'var(--text-primary)' : 'transparent',
  color: primary ? 'var(--app-bg)' : 'var(--text-secondary)',
  border: primary ? 'none' : '1px solid var(--border)',
  padding: '8px 16px', borderRadius: '5px', cursor: 'pointer',
  fontWeight: 500, fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px',
  fontFamily: 'var(--font-primary)',
});

export default OpenFangRawEditor;
