const fs = require('fs');
const path = require('path');
const os = require('os');
const log = require('../logger');
const { writeOpenfangStartSh, writeOpenfangEnv } = require('./shared'); // We'll move start.sh/env generators if needed, or implement them here.

const OpenFangAdapter = {
  id: 'openfang',
  aliases: [],

  readConfig: ({ cwd }) => {
    // Single source of truth for OpenFang: ~/.openfang/config.json
    const configPath = path.join(os.homedir(), '.openfang', 'config.json');
    try {
      if (fs.existsSync(configPath)) {
        const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
        return {
          success: true,
          env: cfg.env || {},
          model: cfg.llm_config?.model || null,
          channels: {}
        };
      }
      return { success: false, reason: 'Config file not found' };
    } catch (err) {
      return { success: false, reason: err.message };
    }
  },

  writeConfig: ({ env, envToRemove, model }) => {
    const configDir = path.join(os.homedir(), '.openfang');
    if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
    
    const configPath = path.join(configDir, 'config.json');
    try {
      let existing = {};
      if (fs.existsSync(configPath)) {
        existing = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      }
      existing.env = { ...(existing.env || {}), ...env };
      if (envToRemove && Array.isArray(envToRemove)) {
        envToRemove.forEach(k => delete existing.env[k]);
      }
      if (model) {
        existing.llm_config = existing.llm_config || {};
        existing.llm_config.model = model;
      }
      
      fs.writeFileSync(configPath, JSON.stringify(existing, null, 2), 'utf8');
      log.info(`[Config] Written config for openfang to`, configPath);

      return OpenFangAdapter.buildToml(configDir, existing, model);
    } catch(e) {
      log.error('[Config] write-platform-config failed:', e.message);
      return { success: false, reason: e.message };
    }
  },

  buildToml: (configDir, existing, model) => {
    let tomlStr = `# ~/.openfang/config.toml — auto-generated by ClawExpress\n\n`;

    const llmConfig = existing.llm_config || {};
    let modelId = llmConfig.model || model || '';
    const activeEnv = { ...existing.env || {} };
    
    // Strip common OpenClaw prefixes
    modelId = modelId.replace(/^(openai\/|anthropic\/|gemini\/|deepseek\/|groq\/|openrouter\/|litellm\/|local\/|custom\/)/i, '');    // ── Read from Connection Hub ─────────────────────────────────────────────
    // ConfigPanel writes:
    //   CLAWEXPRESS_PROVIDER  = provider id (e.g. "custom", "openai", "openrouter"...)
    //   OPENAI_API_KEY        = API key (for custom/local providers)
    //   OPENAI_BASE_URL       = base URL the user typed in Connection Hub
    //   <PROVIDER>_API_KEY    = for named providers (OPENROUTER_API_KEY, etc.)
    let provider = activeEnv.CLAWEXPRESS_PROVIDER || llmConfig.provider || 'openai';

    // ── Provider name → OpenFang native provider ─────────────────────────────
    // OpenFang supports: openai, anthropic, gemini, openrouter, groq, deepseek,
    //                    mistral, xai, moonshot, together, lmstudio, ollama
    const PROVIDER_MAP = {
      custom:     'openai',  // custom proxy = OpenAI-compatible local endpoint
      local:      'openai',
      lmstudio:   'lmstudio',
      ollama:     'ollama',
      google:     'gemini',
      xai:        'xai',
      moonshot:   'moonshot',
      together:   'together',
    };
    const openfangProvider = PROVIDER_MAP[provider] || provider;

    // ── API Key: read from env as-is from Connection Hub ─────────────────────
    // ConfigPanel stores API key for custom/local as OPENAI_API_KEY,
    // for named providers as <PROVIDER_UPPER>_API_KEY
    const pId = provider.toUpperCase();
    const possibleKeyEnvs = [
      `${pId}_API_KEY`,
      'LMSTUDIO_API_KEY',
      'OPENAI_API_KEY',
    ];
    const matchedKeyEnv = possibleKeyEnvs.find(k => activeEnv[k] && activeEnv[k].trim() !== '');
    const apiKeyEnv = matchedKeyEnv ? `"${matchedKeyEnv}"` : '""';

    // ── Base URL: read from Connection Hub, only adjust for Docker networking ─
    // OPENAI_BASE_URL is what ConfigPanel writes for custom/local proxies.
    // For named providers, some have a hardcoded public URL if user didn't override.
    const PUBLIC_BASE_URLS = {
      openrouter: 'https://openrouter.ai/api/v1',
      deepseek:   'https://api.deepseek.com/v1',
      groq:       'https://api.groq.com/openai/v1',
      mistral:    'https://api.mistral.ai/v1',
      together:   'https://api.together.xyz/v1',
      xai:        'https://api.x.ai/v1',
      moonshot:   'https://api.moonshot.cn/v1',
    };

    const possibleBaseUrls = [`OPENAI_BASE_URL`, `${pId}_BASE_URL`, `${pId}_API_KEY_BASE_URL`, 'LOCAL_BASE_URL'];
    const matchedBaseUrlEnv = possibleBaseUrls.find(k => activeEnv[k] && activeEnv[k].trim() !== '');
    let baseUrl = matchedBaseUrlEnv ? activeEnv[matchedBaseUrlEnv] : (PUBLIC_BASE_URLS[openfangProvider] || '');

    // Docker-only transform: localhost/127.0.0.1 → host.docker.internal
    // This handles LM Studio on local machine, but also keeps LAN/remote IPs untouched
    if (baseUrl) {
      baseUrl = baseUrl.replace(/\b(localhost|127\.0\.0\.1)\b/gi, 'host.docker.internal');
    }

    // ── Inject normalized ENV vars for OpenFang ───────────────────────────────
    activeEnv['OPENFANG_LLM_PROVIDER'] = openfangProvider;
    activeEnv['OPENFANG_LLM_MODEL'] = modelId || 'default';
    if (baseUrl && openfangProvider === 'lmstudio') {
      activeEnv['LMSTUDIO_BASE_URL'] = baseUrl;
    }
    if (baseUrl && openfangProvider === 'ollama') {
      activeEnv['OLLAMA_BASE_URL'] = baseUrl;
    }

    tomlStr += `[default_model]\n`;
    tomlStr += `provider = "${openfangProvider}"\n`;
    tomlStr += `model = "${modelId}"\n`;
    tomlStr += `api_key_env = ${apiKeyEnv}\n`;
    if (baseUrl) {
      tomlStr += `base_url = "${baseUrl}"\n`;
    }
    tomlStr += `\n`;

    fs.writeFileSync(path.join(configDir, 'config.toml'), tomlStr, 'utf8');
    log.info(`[Config] Generated config.toml for OpenFang in ${configDir}`);

    const envLines = Object.entries(activeEnv)
      .filter(([k, v]) => !k.startsWith('CLAWEXPRESS_') && v !== undefined && v !== null && v !== '')
      .map(([k, v]) => `${k}=${v}`);
    // Always use LF (\n) — Docker containers are Linux, CRLF (os.EOL on Win) causes corrupted env vars
    fs.writeFileSync(path.join(configDir, '.env'), envLines.join('\n') + '\n', 'utf8');
    log.info(`[Config] Regenerated .env for OpenFang (${envLines.length} var(s)) in ${configDir}`);
    return { success: true };
  },

  readRawConfig: () => {
    const configPath = path.join(os.homedir(), '.openfang', 'config.toml');
    try {
      if (fs.existsSync(configPath)) {
        return { success: true, text: fs.readFileSync(configPath, 'utf8') };
      }
      return { success: false, reason: 'Config file not found' };
    } catch (err) {
      return { success: false, reason: err.message };
    }
  },

  writeRawConfig: ({ text }) => {
    const openfangDir = path.join(os.homedir(), '.openfang');
    const historyDir = path.join(openfangDir, 'history');
    const configPath = path.join(openfangDir, 'config.toml');
    try {
      if (fs.existsSync(configPath)) {
        if (!fs.existsSync(historyDir)) fs.mkdirSync(historyDir, { recursive: true });
        const ts = new Date().toISOString().replace(/[:.]/g, '-');
        const backupPath = path.join(historyDir, `config.toml.rev-${ts}`);
        fs.copyFileSync(configPath, backupPath);
        
        const backups = fs.readdirSync(historyDir)
          .filter(f => f.startsWith('config.toml.rev-'))
          .sort()
          .reverse();
        if (backups.length > 15) {
          backups.slice(15).forEach(f => {
            try { fs.unlinkSync(path.join(historyDir, f)); } catch (_) {}
          });
        }
      }
      
      fs.writeFileSync(configPath, text || '', 'utf8');
      log.info('[Config] Raw TOML config written & backed up successfully');
      return { success: true };
    } catch (err) {
      log.error('[Config] write-raw-openfang-config failed:', err.message);
      return { success: false, reason: err.message };
    }
  },

  getRawConfigHistory: () => {
    const historyDir = path.join(os.homedir(), '.openfang', 'history');
    try {
      if (!fs.existsSync(historyDir)) return { success: true, history: [] };
      const files = fs.readdirSync(historyDir)
        .filter(f => f.startsWith('config.toml.rev-'))
        .sort()
        .reverse()
        .map(f => {
          const m = f.match(/rev-(.*)$/);
          const dateStr = m ? m[1].replace(/-/g, ':') : f;
          return { filename: f, dateStr: dateStr };
        });
      return { success: true, history: files };
    } catch (err) {
      return { success: false, reason: err.message };
    }
  },

  restoreRawConfig: ({ filename }) => {
    const historyDir = path.join(os.homedir(), '.openfang', 'history');
    const target = path.join(historyDir, filename);
    try {
      if (!fs.existsSync(target)) throw new Error('Backup file not found');
      const text = fs.readFileSync(target, 'utf8');
      return { success: true, text };
    } catch (err) {
      return { success: false, reason: err.message };
    }
  },

  channelCheckLinked: () => ({ linked: false }),
  channelLogin: () => ({ success: false, reason: 'not-supported' }),
  channelLogout: () => ({ success: false }),
  channelLoginSuccess: () => ({ success: true }),

  finalizeConfig: (config, writeDir, sendLog) => {
    // Write ~/.openfang/config.json with config
    const configPath = path.join(writeDir, 'config.json');
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf8');

    OpenFangAdapter.buildToml(writeDir, config, config.model);

    try {
      const shared = require('./shared');
      if (shared.writeOpenfangStartSh) shared.writeOpenfangStartSh(sendLog);
      if (shared.writeOpenfangEnv) shared.writeOpenfangEnv(config.env, sendLog);
    } catch(e) {
      log.error('Could not write openfang start scripts', e);
    }
  }
};

function register(fn) { fn(OpenFangAdapter); }
module.exports = { register, OpenFangAdapter };
