const fs = require('fs');
const path = require('path');
const os = require('os');

const OPENFANG_START_SH = [
  '#!/bin/sh',
  '# Auto-generated by ClawExpress. Do not edit manually.',
  '# Waits for openfang (127.0.0.1:50051) then bridges 0.0.0.0:50052 -> 127.0.0.1:50051',
  '# Mock sudo since container runs as root but UI scripts expect it',
  'if ! command -v sudo > /dev/null 2>&1; then',
  '  cat << \'EOF\' > /usr/bin/sudo',
  '#!/bin/sh',
  '# ── Package Alias Registry ──',
  'ALIASES="chromium-browser:chromium other-bad-pkg:good-pkg"',
  'is_apt=0',
  'if [ "$1" = "apt" ] || [ "$1" = "apt-get" ]; then',
  '  if [ "$2" = "install" ]; then',
  '    is_apt=1',
  '    export DEBIAN_FRONTEND=noninteractive',
  '  fi',
  'fi',
  'num=$#',
  'while [ $num -gt 0 ]; do',
  '  mapped="$1"',
  '  for alias_pair in $ALIASES; do',
  '    raw="${alias_pair%%:*}"',
  '    fixed="${alias_pair##*:}"',
  '    if [ "$1" = "$raw" ]; then',
  '      mapped="$fixed"',
  '      break',
  '    fi',
  '  done',
  '  set -- "$@" "$mapped"',
  '  shift',
  '  num=$((num - 1))',
  'done',
  'if [ $is_apt -eq 1 ]; then',
  '  set -- "$@" "-y"',
  'fi',
  'exec "$@"',
  'EXIT_CODE=$?',
  '# Flag that container state changed — triggers docker commit on next stop',
  'if [ $is_apt -eq 1 ] && [ $EXIT_CODE -eq 0 ]; then',
  '  touch /tmp/.needs-commit',
  'fi',
  'exit $EXIT_CODE',
  'EOF',
  '  chmod +x /usr/bin/sudo',
  'fi',
  'if ! command -v socat > /dev/null 2>&1; then',
  '  apt-get update -qq && apt-get install -y socat -qq',
  'fi',
  'openfang start &',
  'OPENFANG_PID=$!',
  'echo "[bridge] Waiting for openfang on 127.0.0.1:50051..."',
  'for i in $(seq 1 30); do',
  '  if grep -q "0100007F:C383" /proc/net/tcp 2>/dev/null; then',
  '    echo "[bridge] openfang is up — starting socat bridge"',
  '    break',
  '  fi',
  '  sleep 1',
  'done',
  'socat TCP-LISTEN:50052,fork,reuseaddr TCP:127.0.0.1:50051 &',
  'wait $OPENFANG_PID',
].join('\n') + '\n';

function writeOpenfangStartSh(sendLog) {
  try {
    const dir = path.join(os.homedir(), '.openfang');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'start.sh'), OPENFANG_START_SH, 'utf8');
    if (sendLog) sendLog(`[INFO] Generated start.sh (socat bridge) in ${dir}`);
  } catch (err) {
    if (sendLog) sendLog(`[WARN] Could not write start.sh: ${err.message}`);
  }
}

function writeOpenfangEnv(env, sendLog) {
  try {
    const dir = path.join(os.homedir(), '.openfang');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const lines = Object.entries(env || {})
      .filter(([k, v]) => !k.startsWith('CLAWEXPRESS_') && v !== undefined && v !== null && v !== '')
      .map(([k, v]) => `${k}=${v}`);
    fs.writeFileSync(path.join(dir, '.env'), lines.join('\n') + '\n', 'utf8');
    if (sendLog) sendLog(`[INFO] Generated .env (${lines.length} var(s)) in ${dir}`);
  } catch (err) {
    if (sendLog) sendLog(`[WARN] Could not write .env: ${err.message}`);
  }
}

module.exports = {
  writeOpenfangStartSh,
  writeOpenfangEnv
};
